global:
  scrape_interval: 15s  # Intervalo de coleta de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: 'web_service'
    static_configs:
      - targets:
          - 'site1:5000'  # Adicionando o container site1

  - job_name: 'web2_service'
    static_configs:
      - targets:
          - 'site2:5000'  # Adicionando o container site2

  - job_name: 'nginx_service'
    static_configs:
      - targets:
          - 'nginx_proxy:80'  # Adicionando o container nginx

  - job_name: 'db_service'
    static_configs:
      - targets:
          - 'db:5432'  # Adicionando o banco de dados
  
  - job_name: 'postgres_exporter'
    static_configs:
      - targets:
        - 'postgres_exporter:9187'
